apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: synopsis-coverity-pvc
  namespace: {{ .Values.agent.namespace }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  volumeMode: Filesystem
