apiVersion: v1
data:
  .dockerconfigjson: ewogICAgImF1dGhzIjogewogICAgICAgICJkb2NrZXIuYXJ0aWZhY3Rvcnkuc2Vydi5jZGMuZnIiOiB7CiAgICAgICAgICAgICJhdXRoIjogImRHVmphRzVwWTJGc0xXcGxibXRwYm5NdGFXTmtZeTF3Y205a09tSjFielYyT1dOaVptUnZlbkJyIgogICAgICAgIH0sCiAgICAgICAgImRvY2tlci5hcnRpZmFjdG9yeS1kZXYuZGkuY2RjLmZyIjogewogICAgICAgICAgICAiYXV0aCI6ICJZV1J0YVc0NlozSmxibTkxYVd4c1pUTXdNVGc9IgogICAgICAgIH0KICAgIH0KfQo=
kind: Secret
metadata:
  name: docker-config
  namespace: {{ .Values.agent.namespace }}
type: kubernetes.io/dockerconfigjson
